import {DefaultTheme} from 'styled-components';
export const BaseTheme: DefaultTheme = {
  colors: {
    primary: {
      dark: '#494b52',
      brand: '#a0c8ff',
      light: '#ffffff',
    },
    accent: {
      success: '#339933',
      error: '#cc0000',
      warning: '#ffcc00',
    },
    neutral: {
      grey10: '#ededee',
      grey40: '#b6b7ba',
      grey60: '#929397',
      black: '#000000',
      grey20: '#dbdbdc',
    },
    opaque: {
      white20: '#ffffff33',
      black20: '#00000033',
      black40: '#00000066',
    },
  },
  fonts: ['Rubik', 'Oswald', 'Roboto'],
  fontSizes: [10, 12, 14, 16, 24, 28, 48],
  fontWeights: [400, 500, 700],
  letterSpacings: [0],
  typography: {
    Headline: {
      H3: {
        fontFamily: 'Rubik',
        fontSize: 16,
        fontWeight: 500,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      H1: {
        fontFamily: 'Oswald',
        fontSize: 28,
        fontWeight: 500,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      HS: {
        fontFamily: 'Oswald',
        fontSize: 48,
        fontWeight: 500,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 56,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      H2: {
        fontFamily: 'Oswald',
        fontSize: 24,
        fontWeight: 500,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      H4: {
        fontFamily: 'Rubik',
        fontSize: 14,
        fontWeight: 500,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
    },
    Paragraph: {
      P1: {
        fontFamily: 'Rubik',
        fontSize: 16,
        fontWeight: 400,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      P2: {
        fontFamily: 'Rubik',
        fontSize: 14,
        fontWeight: 400,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 18,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
    },
    Labels: {
      L1: {
        fontFamily: 'Rubik',
        fontSize: 12,
        fontWeight: 400,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        textAlign: 'left',
        textTransform: 'none',
        textDecoration: 'none',
      },
      L2: {
        fontFamily: 'Roboto',
        fontSize: 10,
        fontWeight: 700,
        fontStyle: 'normal',
        letterSpacing: 0,
        lineHeight: 11.71875,
        textAlign: 'left',
        textTransform: 'uppercase',
        textDecoration: 'none',
      },
    },
  },
  space: {
    '0': 0,
    XS: 4,
    S: 8,
    M: 16,
    L: 20,
  },
  radii: {
    '0': 0,
    S: 4,
    M: 8,
    L: 10,
  },
};
